# Override DB to local Docker MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/albumix?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Local Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

# Local file upload path (create this folder on your Mac)
file.upload-dir=/tmp/albumix/uploads

server.port=8081
